version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "yarn install"
      - run: yarn
      - run: CI=true yarn run build
    test:
      docker:
        - image: cimg/node:14.10.1
        - run: echo 'testing'
        - run: yarn
        - run: yarn test